### ISSUE TITLE
Question on SSIM calculation

### ISSUE THREAD

**Issue by minsuk00** [RomGai/BrainVis#10]
Thank you for the nice paper.
Could you provide details on how you calculated the SSIM scores?
0.75 seems incredibly high for EEG-based image generation, which I'm having difficulties reproducing.
Most fMRI-based methodologies produce around 0.35 and other EEG based papers have around 0.2~0.3.
Thank you!

**Comment by RomGai** [comment]
We have found that our script for calculating SSIM has something wrong. It may probably because the pre-processing (for high-level evaluation) parts in our code, and the actual SSIM should in the range 0.26~0.28.

**Comment by RomGai** [comment]
Considering we do not have any low-level design, we delete this script and replaced SSIM by FID.

**Comment by minsuk00** [comment]
I see! Thank you for confirming.

**Comment by RomGai** [comment]
We have found that our script for calculating SSIM has something wrong. It may probably because the pre-processing (for high-level evaluation) parts in our code. Considering we do not have any low-level design, we delete this script and replaced SSIM by FID. The paper will also be updated later.
