### ISSUE TITLE
OSError: Unable to load weights from checkpoint file for

### ISSUE THREAD

**Issue by qiaoyub** [RomGai/BrainVis#14]
Hello, I encountered the following error while loading StableDiffiusionImg2ImgPipeline.from_stngle_file ("pretrained_madel/v1.5-pruned-emaonly. ckpt"). to (device). I have tried many methods to load it separately, but the same error still occurs

![image](https://github.com/user-attachments/assets/27ad8b85-b8ff-4746-972b-b3d050c184f7)

![image](https://github.com/user-attachments/assets/0f71b772-a634-4475-b46f-977a5816c09e)

**Comment by qiaoyub** [comment]
![image](https://github.com/user-attachments/assets/55438e10-aa39-4d70-b698-ea737c498bbe)
I can save it ,Through the above modifications

but I passed 3090 24 memory, and there was a direct error in the image generation stage. Do you have any good ways to reduce the video memory?
![image](https://github.com/user-attachments/assets/6f7511c2-abc3-4cd9-8c51-e3385923b7b0)

**Comment by RomGai** [comment]
> ![image](https://private-user-images.githubusercontent.com/149659048/362657321-55438e10-aa39-4d70-b698-ea737c498bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzAxODYsIm5iZiI6MTcyNDkyOTg4NiwicGF0aCI6Ii8xNDk2NTkwNDgvMzYyNjU3MzIxLTU1NDM4ZTEwLWFhMzktNGQ3MC1iNjk4LWVhNzM3YzQ5OGJiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMTExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NThhNGI4NTE4NGYwZjcxMDY5ZTBmOWIyZWE2NWVkYjhjNTQ5YzNkN2ZhOGYwNzM3MWY4MDM0YTllYjZhZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WQxdXBCCAE__7DL4fnZwpPcBsoBMItJyLPRAg8nlsFE) I can save it ,Through the above modifications
> 
> but I passed 3090 24 memory, and there was a direct error in the image generation stage. Do you have any good ways to reduce the video memory? ![image](https://private-user-images.githubusercontent.com/149659048/362658699-6f7511c2-abc3-4cd9-8c51-e3385923b7b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzAxODYsIm5iZiI6MTcyNDkyOTg4NiwicGF0aCI6Ii8xNDk2NTkwNDgvMzYyNjU4Njk5LTZmNzUxMWMyLWFiYzMtNGNkOS04YzUxLWUzMzg1OTIzYjdiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMTExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWM5ZjhmMTY0YzA1ZGNmNzRmNzA2NWQ3YWUxOTg3NWU2NGNkODlmNzcxYWY4MGYzZjJkYjc4OTE4YTI2MjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q2Veea2TwVIhp74vMie_Jys2FUoHllcq0DEnRojXyvc)


24G is still much lower than our recommended 40G. If the memory is not enough, try load the sd model in fp16, or reduce the num_samples.
