### ISSUE TITLE
Your checkpoints and a small question

### ISSUE THREAD

**Issue by Nothinkgo** [RomGai/BrainVis#17]
Hello,thanks for your excellent work! I will be much thankful if you can provide me your checkpoints.My email is czy1218989325@163.com. Besides, I want to know wheather I need to uncomment  ' self.train_linear_loader = train_linear_loader' on line 43 of proccess.py and comment out 'self.train_linear_loader = train_loader' on line 42 of proccess.py when I fine-tune the time encoder?
![图片1(1)](https://github.com/user-attachments/assets/0897d2f7-d0de-43cf-ac8c-5e7456e1c77d)

**Comment by RomGai** [comment]
Thank you for your interest in our work. The download link for the checkpoint has been sent to your email.

Additionally, I think there’s no need to make changes to the code in process.py. You can keep it consistent with the code we’ve provided on GitHub.
