### ISSUE TITLE
Attempting to download the necessary config files for this pipeline

### ISSUE THREAD

**Issue by Nothinkgo** [RomGai/BrainVis#18]
Hello,when I run the cascade_diffusion.py, there is somethingwrong happened, such as 
![图片1(2)](https://github.com/user-attachments/assets/5cc37d67-ba9d-4d86-8bd5-cdd40b1229d1)
It happened when I run the code 'model2 =("pretrained_model/v1-5-pruned-emaonly.ckpt").to(device)'. I am sure I have downloaded the right file of v1-5-pruned-emaonly.ckpt and put it in the right content. Acording to the result of the running, it seems to something missing in the file such as config I don't know.Is there any advice to solve the problems?

**Comment by RomGai** [comment]
It looks like the config files are missing. They should have been automatically downloaded, but the attempts are failed.  I suspect it's a network issue.

My suggestion is to search for the missing config files, or download all the relevant SD1.5 files to your local machine and retry: https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/tree/main
