### ISSUE TITLE
EEG Classifier

### ISSUE THREAD

**Issue by zihang-xu** [RomGai/BrainVis#2]
Thank you for your excellent work. Could you please tell me if you do EEG classification in 40 categories? Can you provide more details on the accuracy of the EEG classifier?

**Comment by RomGai** [comment]
Classification is an important component of our work. Table 3 in the paper presents the classification results, and we evaluate the effectiveness of the model in extracting EEG features through classification.

**Comment by zihang-xu** [comment]
Thanks for your reply!

**Comment by RomGai** [comment]
> Thanks for your reply!

Welcome!
