### ISSUE TITLE
Error failed to read image in evaluate python scripts 

### ISSUE THREAD

**Issue by LukasDotEU** [RomGai/BrainVis#4]
In `evalute.py` and `evalute_IS.py` Images in `subj6pic/stage2/` are tried to be opened. However this dir doesn't exist. In `evalute.py` I was able to just comment that part out, because it doesn't do anything. In `evalute_IS.py` it might do something, because the loaded images would be added to the `generated_image_list`.

**Comment by RomGai** [comment]
I have uploaded the modified "evalute.py" and "evalute_IS.py", they should be able to work now. Sorry, the previous one had some redundant parts left from the draft version code that caused the bug.

**Comment by LukasDotEU** [comment]
Thanks for the fast response. Thanks for publishing the repository btw!
