### ISSUE TITLE
Your checkpoints and a small question

### ISSUE THREAD

**Issue by Annguyen1512** [RomGai/BrainVis#7]
Can you provide the checkpoints for me? Your model is wonderful, I appreciate you. My email is aiclhcm01@gmail.com.

I also have a question: What's your TeA at max VA when you run the train_freqencoder.py? Hope you reply soon. Thank you very much!

**Comment by RomGai** [comment]
Please check your email.

Besides, the TeA means Test Accuracy, and 'TeA at max VA' is just used for a reference, which we keep from the code provided by the dataset creator.
