### ISSUE TITLE
Pretrain epoch file

### ISSUE THREAD

**Issue by jennycrewemalaya** [RomGai/BrainVis#8]
Do you keep the finetuned time encoder "finetune_model_epoch80.pkl", the file is in process.py? Because my GPU is limited so could you please send me the .pkl file if you still keep it, via my email: jennycrewe1507@gmail.com? Thank you very much.

**Comment by RomGai** [comment]
I am so sorry for not keeping the fine-tuned time encoder. If you only need the time encoder, you can change the batch size in 'args.py' for training. I think a 16G GPU is enough with a smaller batch size (for example, 32). However, smaller batch size may also lead to worse performance.

Besides, I have saved the model for image generation. Please inform me if you need it.

**Comment by jennycrewemalaya** [comment]
So sorry that you no longer keep it, but thank you anyway. I have run the mini model for image generation already.

**Comment by RomGai** [comment]
Sorry again, hope your experiment goes well and that our work can be of any help to you.
